workflows:
  build_app:
    name: Build CGAPP
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build apk --debug
      - flutter build web --release
    artifacts:
      - build/**/*
